fix: fix register config failed

diff --git a/Taskfile.yaml b/Taskfile.yaml
--- a/Taskfile.yaml
+++ b/Taskfile.yaml
@@ -10,3 +10,26 @@ tasks:
     - task: frontend:generate
     - task: frontend:build
     - wails dev -skipbindings -s -noreload -v=2
+  test:
+    - task: test:backend
+  test:backend:
+    - test -d build/coverage || mkdir -p build/coverage
+    - go test -coverprofile=build/coverage/coverage.out ./...
+    - go tool cover -func=build/coverage/coverage.out
+  test:threshold:
+    cmd: |
+      totalCoverage=`go tool cover -func=build/coverage/coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+      
+      echo "Quality Gate: checking test coverage is above threshold ..."
+      echo "Threshold             : $TEST_COVERAGE_THRESHOLD %"
+      echo "Current test coverage : $totalCoverage %"
+      
+      if (( $(echo "$totalCoverage >= $TEST_COVERAGE_THRESHOLD" | bc -l) )); then
+          echo "Result                : Pass"
+      else
+          echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+          echo "Result                : Failed"
+          exit 1
+      fi
+    env:
+      TEST_COVERAGE_THRESHOLD: 33.9
